# Generated by Django 5.2.4 on 2025-10-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_users_is_admin_users_last_login_alter_users_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
