# Generated by Django 5.2.4 on 2025-10-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_booking_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dp',
            field=models.CharField(default='Unknown', max_length=500),
        ),
    ]
